#!/bin/sh
set -e
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.py')
REF_SHEBANG="#!/usr/bin/env python3"

if [[ -n "$CHANGED_FILES" ]]; then
    for f in $CHANGED_FILES; do
        SHEBANG=$(head -n 1 $f | awk '{ gsub(/^[ \t\n]+|[ \t\n]+$/, ""); print}')
        if [[ ( -x $f ) && ( "$SHEBANG" !=  "$REF_SHEBANG" ) ]]; then
            echo "Shebang of $f doesn't match $REF_SHEBANG"
            exit 1
        fi
    done

    isort --profile black $CHANGED_FILES
    black --target-version py39 --safe $CHANGED_FILES
    git add $CHANGED_FILES

    mypy --strict *.py
    pytype -j 10 *.py

    cat $CHANGED_FILES | awk '/pdb.set_trace/ || /import pdb/ || /reveal_type/ { print $0; f=1 } END { exit f }'
 
fi
