on: [ push ]
name: Lint Python and Format
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install mypy .
      - name: run mypy
        run: python -m mypy --strict 
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install black
      - name: Check formating with black
        run: python -m black --check dead
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install flake8
      - name: run flake8
        run: python -m flake8 dead
  isort:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: python -m pip install isort
        - name: Check imports with isort
          run: python -m isort --profile black --check dead
