on: [ push, pull_request ]
name: Lint Python and Format
jobs:
  mypy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements_hook.txt
      - name: run mypy
        run: python3 -m mypy --strict *.py 
  black:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements_hook.txt
      - name: Check formating with black
        run: python3 -m black --check *.py
  pytype:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements_hook.txt
      - name: run pytype
        run: python3 -m pytype *.py
