on: [ push, pull_request ]
name: Lint Python and Format
jobs:
  mypy:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt mypy
      - run: mypy --install-types --non-interactive
      - name: run mypy
        run: python3 -m mypy --strict *.py 
  black:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt 'black<=22.12.0'
      - name: Check formating with black
        run: python3 -m black --check *.py
  pytest:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt pytest
      - name: run pytest
        run: python3 -m pytest 
